name: 机器人后端服务
run-name: ${{ github.actor }} 简单机器人应答
on:
  push:
    branches:
      - dev
    schedule:
      - cron: "11 */3 * * *"
  workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
  RUNTIME: 10800 #运行多少秒

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: 导入引用库
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 主要作业
        run: |
          python main.py
